// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using schoolDAL.Models;

#nullable disable

namespace schoolDAL.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20250619175928_MigrationName")]
    partial class MigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT")
                        .HasColumnName("ID");

                    b.Property<string>("Address")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int?>("BirthdayYear")
                        .HasColumnType("INT");

                    b.Property<string>("Class")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("HomePhone")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT")
                        .HasColumnName("ID");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("MailAddress")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("schoolDAL.Models.HomeroomTeacherOfClass", b =>
                {
                    b.Property<string>("Class")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<int?>("IdTeacher")
                        .HasColumnType("INT");

                    b.ToTable("HomeroomTeacherOfClass", (string)null);
                });

            modelBuilder.Entity("schoolDAL.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INT")
                        .HasColumnName("ID");

                    b.Property<string>("SubjectName")
                        .HasColumnType("VARCHAR(10)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("schoolDAL.Models.TeacherOfSubjectInClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<int?>("IdSubject")
                        .HasColumnType("INT");

                    b.Property<int?>("IdTeacher")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.ToTable("TeacherOfSubjectInClass", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
